services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    ports:
      - "5011:8081"
    volumes:
      - ./metube_downloads:/downloads
    # restart: unless-stopped
    # network_mode: "service:vpn"
    # depends_on:
    #   - vpn
    

  # vpn:
  #   image: qmcgaw/gluetun
  #   container_name: vpn
  #   cap_add:
  #     - NET_ADMIN
  #   env_file:
  #     - .env
  #   dns:
  #     - 1.1.1.1
  #     - 8.8.8.8
  #   ports:
  #     - 5010:8081   # expose MeTube UI via VPN container
  #   restart: unless-stopped


  